### ISSUE TITLE
scanFailure event is being triggered constantly with Angular 8

### ISSUE THREAD

**Issue by ngeor** [zxing-js/ngx-scanner#209]
**Describe the bug**
scanFailure event is being triggered constantly with Angular 8.

The stack trace is this:

```
No MultiFormat Readers were able to detect the code.
    at l.decodeInternal (https://angular-usl95g.stackblitz.io/turbo_modules/@zxing/library@0.14.2/umd/index.min.js:1:124857)
    at l.decodeWithState (https://angular-usl95g.stackblitz.io/turbo_modules/@zxing/library@0.14.2/umd/index.min.js:1:123702)
    at BrowserMultiFormatContinuousReader.f.decodeBitmap (https://angular-usl95g.stackblitz.io/turbo_modules/@zxing/library@0.14.2/umd/index.min.js:1:166444)
    at BrowserMultiFormatContinuousReader.p.decode (https://angular-usl95g.stackblitz.io/turbo_modules/@zxing/library@0.14.2/umd/index.min.js:1:31153)
    at BrowserMultiFormatContinuousReader.decodeOnSubject (https://angular-usl95g.stackblitz.io/turbo_modules/@zxing/ngx-scanner@1.7.1/bundles/zxing-ngx-scanner.umd.js:560:35)
    at eval (https://angular-usl95g.stackblitz.io/turbo_modules/@zxing/ngx-scanner@1.7.1/bundles/zxing-ngx-scanner.umd.js:580:59)
    at ZoneDelegate.invokeTask (https://angular-usl95g.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:423:31)
    at Object.onInvokeTask (https://angular-usl95g.stackblitz.io/turbo_modules/@angular/core@8.0.1/bundles/core.umd.js:24385:37)
    at ZoneDelegate.invokeTask (https://angular-usl95g.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:422:60)
    at Zone.runTask (https://angular-usl95g.stackblitz.io/turbo_modules/zone.js@0.9.1/dist/zone.js:195:47)
```

**To Reproduce**

I have an app in StackBlitz that demonstrates the problem:

https://angular-usl95g.stackblitz.io

Basically, you just need to add this on an Angular 8 app:

```
  <zxing-scanner
      class="fit-video"
      [enable]="true"
      (scanFailure)="handleFailure($event)"
    ></zxing-scanner>
```

with this event handler:

```
  handleFailure(e) {
    console.log(e);
  }
```

And then you get flooded in errors.

In our application, we're disabling the scan flow if the scanner emits an error, so it's a blocker for us, preventing us from upgrading to Angular 8.

**Expected behavior**
There should not be any failures being logged.

**Desktop (please complete the following information):**
 - OS: Mac and Windows (also Android phone)
 - Browser: Chrome
 - Version: 75

**Comment by odahcam** [comment]
> No MultiFormat Readers were able to detect the code.

This is no an error, this is a failure to decode a barcode in the current image stream, it means it is expected.

If you wanna look for unexpected errors that may cause the scanner to not work anymore, go with `scanError`.

Thanks.

**Comment by ngeor** [comment]
Thank you @odahcam , apologies for the misunderstanding. We'll change the handler to `scanError` as you mentioned.

**Comment by odahcam** [comment]
No problem, feel free to open new issues as you need.
